# Generated by Django 4.2 on 2025-12-06 17:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import playlist.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.CharField(default=playlist.models.gen_track_id, max_length=40, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=200)),
                ('album', models.CharField(blank=True, max_length=200, null=True)),
                ('duration_seconds', models.IntegerField()),
                ('genre', models.CharField(blank=True, max_length=100, null=True)),
                ('cover_url', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlaylistTrack',
            fields=[
                ('id', models.CharField(default=playlist.models.gen_playlist_id, max_length=40, primary_key=True, serialize=False)),
                ('position', models.FloatField(db_index=True)),
                ('votes', models.IntegerField(default=0)),
                ('added_by', models.CharField(default='Anonymous', max_length=100)),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_playing', models.BooleanField(default=False)),
                ('played_at', models.DateTimeField(blank=True, null=True)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playlist.track')),
            ],
        ),
    ]
